version: "3.8"

services:
  # 1. Database
  postgres:
    image: postgres:15-alpine
    container_name: football_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis for Queues (BullMQ)
  redis:
    image: redis:alpine
    container_name: football_redis
    restart: always
    ports:
      - "6379:6379"

  # 3. Database Management UI (Optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: football_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
